{
 "title": "CP4D Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Container Memory Use % Warning",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sort_desc((sum by (container_name) (container_memory_working_set_bytes{namespace=\"zen\", name!~\".*prometheus.*\", name!~\".*redis.*\", image!=\"\", container_name!=\"POD\"}) / sum by (container_name) (container_spec_memory_limit_bytes{namespace=\"zen\", name!~\".*prometheus.*\", name!~\".*redis.*\", image!=\"\", container_name!=\"POD\"})) * 100) >= 50 and sort_desc((sum by (container_name) (container_memory_working_set_bytes{namespace=\"zen\", name!~\".*prometheus.*\", name!~\".*redis.*\", image!=\"\", container_name!=\"POD\"}) / sum by (container_name) (container_spec_memory_limit_bytes{namespace=\"zen\", name!~\".*prometheus.*\", name!~\".*redis.*\", image!=\"\", container_name!=\"POD\"})) * 100) <= 100)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Top 5 CPU consuming Services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{namespace=\"zen\", name!~\".*prometheus.*\", name!~\".*redis.*\", image!=\"\", container_name!=\"POD\"}[30m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{namespace=\"zen\", name!~\".*prometheus.*\", name!~\".*redis.*\",  image!=\"\", container_name!=\"POD\"}/container_spec_cpu_period{namespace=\"zen\", name!~\".*prometheus.*\", name!~\".*redis.*\",  image!=\"\", container_name!=\"POD\"}) by (pod_name, container_name))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Top Container Restarts",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "topk(20, kube_pod_container_status_restarts_total{namespace=\"zen\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Top 5 memory consuming services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (instance, service) (rate(container_memory_max_usage_bytes[5m])))"
    }
   ]
  }
 ]
}