{
 "title": "Cloud Pak Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Container OOM Warning Meter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(topk(5, max(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\", pod!=\"\"}) by (pod) ) / sum(container_memory_max_usage_bytes{namespace=\"$namespace\"}) by (pod)) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 CPU Consuming Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(max(kube_pod_labels{namespace=~\"$namespace\", pod!=\"\", label_component!=\"\"}) by (label_component,pod) * on(pod) group_right(label_component) max(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}) by(pod)) by (label_component))",
     "legendFormat": "{{label_component}}"
    }
   ]
  },
  {
   "title": "Container Restarts in Last Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[60m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Top 10 memory consuming services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(max(kube_pod_labels{namespace=\"$namespace\"}) by (label_release,pod) * on(pod) group_right(label_release) max(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by(pod)) by (label_release) / 1e+9)",
     "legendFormat": "{{label_release}}"
    }
   ]
  },
  {
   "title": "Container CPU Limit Warning Meter",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "topk(5, 100 * (sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Namespace CPU Usage in Last 60 Minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "namespace:container_cpu_usage:sum{namespace='$namespace'}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Memory Usage in Last 60 Minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{namespace=\"$namespace\",container=\"\",pod!=\"\"}) / 1e+9",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of API Calls in Last 60 Minutes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(apiserver_request_count{verb=~\"POST|PUT|DELETE|PATCH|GET|LIST|WATCH\"}[60m]))",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}