{
 "title": "cp4d-Test",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Container OOM Warning Meter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(topk(5, max(container_memory_working_set_bytes{namespace=\"zen\",container!=\"\", pod!=\"\"}) by (pod) ) / sum(container_memory_max_usage_bytes{namespace=\"zen\"}) by (pod)) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5 CPU Consuming Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"zen\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Restart Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total[60m]))"
    }
   ]
  },
  {
   "title": "Top 5 memory consuming services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{namespace=\"zen\",container!=\"\"}) by (pod)) / 1e+6"
    }
   ]
  },
  {
   "title": "Container CPU Limit Warning Meter",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "100 * sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"zen\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"zen\"}) by (pod)"
    }
   ]
  }
 ]
}